#!/bin/bash
### Job Name
#PBS -N train_holo
### Project code
#PBS -A NEOL0007
#PBS -l walltime=12:00:00
#PBS -q casper
### Merge output and error files
### PBS -j oe
### Select 1 node with 1 CPU and 1 A100 GPU
#PBS -l select=1:ncpus=1:mpiprocs=1:mem=100GB:ngpus=1 -l gpu_type=a100
### Send email on abort, begin and end
###PBS -m abe
### Specify mail recipient
#PBS -M mhayman@ucar.edu

# export PYTHONPATH=$PYTHONPATH:$HOME/Python/miles-holodec/

export TMPDIR=/glade/derecho/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/miles-holodec

module load conda

conda activate holodec

# source ~/.bash_profile

### Run the executable
python applications/trainer_unet.py -c config/best.yml