log: True
save_path: "/glade/work/schreck/repos/miles-holodec/results/echo/"

pbs:
  jobs: 30
  tasks_per_worker: 1
  gpus_per_node: 1
  bash: [
      "source ~/.bashrc", 
      "conda activate holodec"
        ]
  batch:
    N: "echo-holo"
    l: ["select=1:ncpus=8:ngpus=1:mem=128GB", "walltime=12:00:00", "gpu_type=a100"]
    A: "NAML0001"
    q: "casper"
    o: "out"
    e: "out"

optuna:
  storage: "study.db"
  study_name: "holodec"
  storage_type: "sqlite"
  objective: "/glade/work/schreck/repos/miles-holodec/applications/train.py"
  direction: "minimize"
  metric: "valid_loss"
  n_trials: 1000
  gpu: True
  sampler:
    type: "TPESampler"
    n_startup_trials: 100
  parameters:
    optimizer:learning_rate:
      type: "loguniform"
      settings:
        name: "learning_rate"
        low: 5.0e-05
        high: 1.0e-02
    trainer:training_loss:
      type: "categorical"
      settings:
        name: "training_loss"
        choices: ["dice", "dice-bce", "iou", "focal", "tyversky", "focal-tyversky", "lovasz-hinge", "combo"]
    model:name:
      type: "categorical"
      settings:
        name: "model_name"
        choices: ["unet", "unet++", "manet", "linknet", "fpn", "pspnet", "pan", "deeplabv3", "deeplabv3+"]
    model:encoder_name:
      type: "categorical"
      settings:
        name: "encoder_name"
        choices: ["resnet18", "resnet152", "densenet121", "xception", "efficientnet-b0", "mobilenet_v2", "dpn68", "vgg11"]
    # transforms:training:GaussianBlur:sigma:
    #   type: "float"
    #   settings:
    #     name: "sigma"
    #     low: 0.0
    #     high: 5.0
    # transforms:training:GaussianNoise:noise:
    #   type: "float"
    #   settings:
    #     name: "noise"
    #     low: 0.0
    #     high: 1.0
    # transforms:training:AdjustBrightness:brightness_factor:
    #   type: "float"
    #   settings:
    #     name: "brightness_factor"
    #     low: 0.0
    #     high: 5.0
    transforms:training:Normalize:mode:
      type: "categorical"
      settings:
        name: "mode"
        choices: ["norm", "stan", "sym", "255"]
