seed: 1000
save_loc: "/glade/work/schreck/repos/miles-holodec/results/zzz/"

data:
    n_bins: 1000
    data_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_training.nc"
    raw_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_203600-203700.nc"
    tile_size: 512
    step_size: 128
    marker_size: 10
    total_positive: 6
    total_negative: 6
    total_training: 100000
    transform_mode: 'None'
    output_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/"
    use_cached: True
    device: "cpu"
    cores: 0

transforms:
    training:
        ToTensor: True
        RandomVerticalFlip:
            rate: 0.5
        RandomHorizontalFlip: 
            rate: 0.5
        PlanerNormalize:
            mode: 'norm'
        GaussianBlur:
            rate: 1.0
            kernel_size: 1
            sigma: 2.1252219359742823
        GaussianNoise:
            rate: 1.0
            noise: 0.3258530643453389
        AdjustBrightness:
            rate: 1.0
            brightness_factor: 1.269735791766263
    validation:
        PlanerNormalize:
            mode: 'norm'
        ToTensor: True
    inference:
        PlanerNormalize:
            mode: 'norm'
            
            
model:
    name: "linknet"
    encoder_name: "xception"
    encoder_weights: "imagenet"
    in_channels: 1
    classes: 1
    activation: "sigmoid"
    
optimizer:
    learning_rate: 0.00024575732726722595
    weight_decay: 0.0

loss: 
    training_loss_mask: "focal-tyversky"
    validation_loss_mask: "dice"
    
trainer:
    mode: "none" # none, ddp, fsdp
    train_batch_size: 4
    valid_batch_size: 4
    batches_per_epoch: 5 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 5
    learning_rate: 2.4575732726722595e-04 # 5.0e-04
    weight_decay: 0.0 # 1.0e-05
    start_epoch: 0
    epochs: 10
    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0
    thread_workers: 4
    valid_thread_workers: 4
    stopping_patience: 4
    use_scheduler: True
    scheduler: {
        scheduler_type: 'cosine-annealing', 
        first_cycle_steps: 500, 
        cycle_mult: 6.0, 
        max_lr: 2.4575732726722595e-04, 
        min_lr: 2.4575732726722595e-07, 
        warmup_steps: 499, 
        gamma: 0.7
        }
    
inference:
    mode: "mask"
    batch_size: 16
    n_nodes: 4
    gpus_per_node: 1
    threads_per_gpu: 2
    save_arrays: True
    save_probs: False
    probability_threshold: 0.5
    plot: False
    verbose: False
    data_set:
#         path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_test.nc"
#         name: "synthetic"
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
        name: "real"
        holograms:
            min: 10
            max: 20