seed: 1000
save_loc: "/glade/work/schreck/repos/miles-holodec/results/zzz/"

data:
    n_bins: 1000
    data_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_training.nc"
    raw_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_203600-203700.nc"
    tile_size: 512
    step_size: 128
    marker_size: 10
    total_positive: 6
    total_negative: 6
    total_training: 100000
    transform_mode: 'None'
    output_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/"
    use_cached: True
    device: "cpu"
    cores: 0

train_dataset:
    path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/train_512_128_6_6_100000_None.nc"

validation_dataset:
    path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/valid_512_128_6_6_100000_None.nc"

transforms:
    training:
        ToTensor: True
        RandomVerticalFlip:
            rate: 0.5
        RandomHorizontalFlip: 
            rate: 0.5
        Normalize:
            mode: 'norm'
        GaussianBlur:
            rate: 1.0
            kernel_size: 1
            sigma: 2.1252219359742823
        GaussianNoise:
            rate: 1.0
            noise: 0.3258530643453389
        AdjustBrightness:
            rate: 1.0
            brightness_factor: 1.269735791766263
    validation:
        Normalize:
            mode: 'norm'
        ToTensor: True
    inference:
        Normalize:
            mode: 'norm'
            
            
model:
    name: "linknet"
    encoder_name: "xception"
    encoder_weights: "imagenet"
    in_channels: 1
    classes: 1
    activation: "sigmoid"
    
optimizer:
    lr: 0.00024575732726722595
    weight_decay: 0.0

loss: 
    training_loss_mask: "focal-tyversky"
    validation_loss_mask: "dice"
    
trainer:
    mode: "ddp" # none, ddp, fsdp
    train_batch_size: 16
    valid_batch_size: 16
    batches_per_epoch: 500 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 100
    start_epoch: 0
    epochs: 100
    amp: False
    thread_workers: 4
    valid_thread_workers: 4
    stopping_patience: 4
    use_scheduler: True
    scheduler: {scheduler_type: plateau, mode: min, factor: 0.1, patience: 5, cooldown: 2, min_lr: 1.0e-06, verbose: true, threshold: 1.0e-04}
    # scheduler: {'scheduler_type': 'lambda'}
    # scheduler: {
    #     scheduler_type: 'cosine-annealing', 
    #     first_cycle_steps: 500, 
    #     cycle_mult: 6.0, 
    #     max_lr: 2.4575732726722595e-04, 
    #     min_lr: 2.4575732726722595e-07, 
    #     warmup_steps: 499, 
    #     gamma: 0.7
    #     }
    
inference:
    mode: "mask"
    batch_size: 16
    n_nodes: 4
    gpus_per_node: 1
    threads_per_gpu: 2
    save_arrays: True
    save_probs: False
    probability_threshold: 0.5
    plot: False
    verbose: False
    data_set:
#         path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_test.nc"
#         name: "synthetic"
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
        name: "real"
        holograms:
            min: 10
            max: 20

# pbs: #derecho
#     conda: "holodec"
#     project: "NAML0001"
#     job_name: "holodec"
#     walltime: "12:00:00"
#     nodes: 1
#     ncpus: 64
#     ngpus: 4
#     mem: '487GB'
#     queue: 'preempt'
    
pbs: # casper
    conda: "holodec"
    job_name: 'unet'
    nodes: 1
    ncpus: 8
    ngpus: 4
    mem: '128GB'
    walltime: '12:00:00'
    gpu_type: 'a100'
    project: 'NAML0001'
    queue: 'casper'